# POST https://trietix-server-2.onrender.com/api/v1/ticket
POST https://trietix-server-2.onrender.com/api/v1/ticket/webhook/paystack
content-type: application/json

{
    "email": "abduhameedyakubu123@gmail.com",
    "ticketId": "T236935350780642",
    "processingFee": 350,
    "amount": 1,
    "price": 3850,
    "event": "673a408efc49daa2e398253e",
    "isCheckedIn": false,
    "noOfCheckedIn": 0
}