name: Build and deploy

on: 
    push:
        branches:
            - main
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 16
                
        - name: Install dependencies
          run: npm ci

        - name: Build
          run: npm run compile

        - name: Copy code
          run: |
              mkdir temp_lib
              cp -R lib/* temp_lib/

    deploy:
        runs-on: ubuntu-latest
        needs: [build]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Create Github release
              uses: google-github-actions/release-please-action@v3
              id: release
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                release-type: node
                package-name: package-test
                changelog-types: '[{"type":"feat", "section": "Features", "hidden": false}, {"type": "fix", "section": "Bug", "hidden": false}, {"type": "refactor", "section": "Refactor", "hidden": false}, {"type": "chore", "section": "Miscelaneous", "hidden": false},{"type": "docs", "section": "Documentation", "hidden": false}, {"type":"style","section ": "Linting", "hidden": false}, {"type":"perf", "section":"Performance", "hidden": false},{"type": "test", "section": "Test", "hidden": false}, {"type": "build", "section": "Build", "hidden": false},{"type":"ci","section":"CI/CD","hidden": false},{"type": "revert", "section": "Revert Commit", "hidden": false}]' 

            - name: Deploy to production
              uses: johnbeynon/render-deploy-action@v0.0.8
              with: 
                  api-key: ${{ secrets.RENDER_TOKEN }}
                  service-id: ${{ secrets.SERVICE_ID }}
                